name: xmonad-matthew
version: 0.1.0
synopsis: xmonad setting
github: Mdsp9070/dotfiles
author: Zoey
maintainer: mdsp@boosting.tech
copyright: © Zoey de Souza Pessanha
license: MIT
dependencies:
  - X11
  - base
  - xmonad
  - xmonad-contrib
library:
  source-dirs: lib
  dependencies:
    - containers
executables:
  xmonad:
    main: xmonad.hs
    ghc-options:
      - -Wall
      - -fwarn-tabs
      - -threaded
      - -O2
      - -with-rtsopts=-N4
